server:
  port: 1111
spring:
  application:
    name: STOCK-PRICE-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytraining
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
    
    
     
